### PR TITLE
state explicitly that const-items are copied bitwise

### PR DESCRIPTION
**Pull request by RalfJung**
This certainly describes the current reality.

Cc @ecstatic-morse

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
As I noted on Zulip, I think we should leave this deliberately unspecified until we have a strategy for [heap allocation in constants](https://github.com/rust-rfcs/const-eval/issues/20#issuecomment-520227200). I don't think we gain much by specifying this today? Although I guess this repo is non-normative, so explaining this as the *current* behavior would be fine.

Basically, the issue is around code like:

```rust
const ONE: Box<i32> = Box::new(1);

let a = ONE;
let b = ONE;
```

My intuitive understanding of `const` is that it behaves as though you copy-pasted the initializer everywhere the `const` was used, in which case this should compile. However, if bitwise-copies are used everywhere, obviously this code obviously must be rejected.

**Comment by RalfJung** [comment]
> I don't think we gain much by specifying this today

I think we gain a lot in clarity.^^ The only reason this sentence isn't there already is that when writing this document, I considered it so obvious that it wasn't worth stating...

> My intuitive understanding of const is that it behaves as though you copy-pasted the initializer everywhere the const was used

It behavs *as-if* but without actually doing that, that's the entire point. `const` would be rather useless if it was actual copy-paste... or at least the name would be quite the misnomer. There is nothing *constant* about them any more!

**Comment by ecstatic-morse** [comment]
My understanding is that specifying that a `const` always uses bitwise copies means that, under *all* possible proposals for heap allocation in constants, the above example *must* fail to compile. Is this correct?

If so, then I think this should at least be discussed in rust-rfcs/const-eval#20 before a decision is made here. I'm not convinced that the previous example must be accepted, but I don't think it's outside the realm of possibility.

**Comment by RalfJung** [comment]
I expected that to be a constraint anyway, but I'll add a clause clarifying that this is current behavior.
And in any case, nothing in this repo is normative -- these are just docs.

**Comment by RalfJung** [comment]
@ecstatic-morse e.g., everything [we say here](https://github.com/rust-rfcs/const-eval/blob/master/const.md#references) is also just describing current behavior and could be changed if we wanted to.

**Comment by ecstatic-morse** [comment]
True. In any case, we should try to reach consensus about this when @oli-obk is back from vacation.

I would r+ the new changes if I had the permissions btw.

**Comment by RalfJung** [comment]
> I would r+ the new changes if I had the permissions btw.

That sounds good enough for such a small change. ;)

**Pull request merged**
